### ISSUE TITLE
Update-GhcmanVersionFile : 404 Not Found

### ISSUE THREAD

**Issue by yokodake** [kakkun61/ghcman#19]
# Describe the bug

When invoking `Update-GhcmanVersionFile` the following error is raised:
```
PS C:\> Update-GhcmanVersionFile
Invoke-WebRequest: 404: Not Found
```

I don't know much about PS but i think the `[Version]` "attribute" when setting the `$ghcmanVersion` is at fault [here](https://github.com/kakkun61/ghcman/blob/master/ghcman.psm1#L7):
```
PS C:\> Set-Variable ghcmanVersion -Option Constant -Value [Version]"4.8"
PS C:\> $ghcmanVersion
[Version]4.8
PS C:\> Write-Output "https://raw.githubusercontent.com/kakkun61/ghcman/master/version.$ghcmanVersion.yaml"
https://raw.githubusercontent.com/kakkun61/ghcman/master/version.[Version]4.8.yaml
PS C:\> Invoke-WebRequest "https://raw.githubusercontent.com/kakkun61/ghcman/master/version.$ghcmanVersion.yaml"
Invoke-WebRequest: 404: Not Found

PS C:\>  Set-Variable ghcmanVersion -Option Constant -Value "4.8"
PS C:\> $ghcmanVersion
4.8
PS C:\> Invoke-WebRequest "https://raw.githubusercontent.com/kakkun61/ghcman/master/version.$ghcmanVersion.yaml"

StatusCode        : 200
StatusDescription : OK
Content           : ...
```

# To Reproduce

Following the Readme:
1. Run Cmdlet `Import-Module ghcman`
2. Run Cmdlet `Get-Module ghcman`
3. Run Cmdlet `Update-GhcmanVersionFile`
4. See error 'Invoke-WebRequest: 404: Not Found`

# Expected behavior

The cmdlet invocation to succeed and the versionfile to be updated.

# Environment

 - OS: [e.g. Windows 10 19044]
 - PowerShell:
 ```
 Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
 - Version: 4.8

**Comment by kakkun61** [comment]
Thank you for your report. I'll check this later.

**Comment by kakkun61** [comment]
I released 4.9 with this fix.

https://github.com/kakkun61/ghcman/releases/tag/4.9

**Comment by kakkun61** [comment]
Please reopen this issue if it happens again.

**Comment by kakkun61** [comment]
I found that this issue was still occurred. Hmm, my local development package does not occur this.

**Comment by kakkun61** [comment]
Fixed.
